# CMS service only
version: '3.8'

services:
  cms:
    build:
      context: .
      dockerfile: apps/cms/Dockerfile
    environment:
      - SANITY_STUDIO_PROJECT_ID=${NEXT_PUBLIC_SANITY_PROJECT_ID}
      - SANITY_STUDIO_DATASET=${NEXT_PUBLIC_SANITY_DATASET}
    restart: unless-stopped
    networks:
      - cms-network
    ports:
      - "3333:3333"

networks:
  cms-network:
    driver: bridge