[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.build]
cmds = [
  "cd apps/backend && pnpm install --frozen-lockfile",
  "cd apps/backend && pnpm run build"
]

[phases.start]
cmd = "cd apps/backend && pnpm run start"

[variables]
NODE_ENV = "production"