[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/backend/Dockerfile.railway"
rootDirectory = "apps/backend"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10